### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by rydlers** [Nxve/AutoMudaeExt#1]
Hello @Nxve, I really loved the idea of your extension and I really want to try it out, But I'm not very experienced on Github, So I don't even know how to download install or run it. So if you were that gentle to let me know that I would be very grateful.

And two questions that I have, Do I need the tab and/or browser focused while using it, or both browser and tab can be in the background?

Thank you very much.

**Comment by Nxve** [comment]
It's really unstable in its current state, hence the unavailability to public use. You could theoretically clone this repository, build it and import to your Chrome from local files, but i don't recommend it.

There's a roadmap in this repository readme that may give you an expectation of when it will become available.

And it's intended to work in background.
