### ISSUE TITLE
Release ?

### ISSUE THREAD

**Issue by NameLess0974** [Nxve/AutoMudaeExt#4]
Hello, I'm sorry about my question. However, I came across you by chance, I'm very interested and as you've been working on this for quite some time, I was wondering, are we still far from a first test version or not at all?

**Comment by Nxve** [comment]
In terms of functionality, it's pretty much ready to use, but i've been really busy, so i haven't had time to publish it at webstore.

There's some people using it already, sending feedback, requesting features and stuff. Contact me at discord if you have any interest in using it while in development. My handle is **nxve**.
